### ISSUE TITLE
Any solutions or suggestions of Convergence problem with tetrahedral grids?

### ISSUE THREAD

**Issue by fengzekang** [phorgue/porousMultiphaseFoam#14]
Hello, everyone
I meet the converge problem that there is no converge with the tetrahedral grids. I have tried to change the cell size, the time step dt and also I changed the CFL number, but no good results... I find a link which is discussion about the "Convergence problem with tetrahedral grids?" https://www.cfd-online.com/Forums/openfoam-solving/82696-convergence-problem-tetrahedral-grids.html 
I found that somebody tried to change the solver and schemes to solve it. but there is not a reasonable solution....anybody used the  tetrahedral grids and did you meet this problem?

**Comment by FoamScience** [comment]
That thread is quite old, Before OF3, meshing wasn't that great but now you should have no problems with tetrahedral meshes. It depends on what solvers you use but the first thing to try is to increase non-orthogonal correctors and fallback to upwind-like schemes. We need more details on the subject!

**Comment by fengzekang** [comment]
Thakns for your reply. As what I am doing is about the porousMulti( I used the porousInter application) based on OF6, not as same as this application but they are similar. 
As for the mesh, I just define a cube with hex-grids which are good and going well. But if I used the tetrahedral grids, the simulation will not converge. I use checkMesh to chech the mesh quality, 
![Screenshot from 2019-09-16 15-47-25](https://user-images.githubusercontent.com/38140045/64941620-c3ea0300-d899-11e9-8e3f-679a28410b5e.png)

As for the real simulation, I want to make a model like following:
![Screenshot from 2019-08-19 22-27-30](https://user-images.githubusercontent.com/38140045/64941741-01e72700-d89a-11e9-9a30-4b4ffda89f10.png)
left side, there is a cube region with water, and middle region there is the porousity regions. this looks like a sample a water go through a "dam".

following is my total project.
[dam_example7.tar.gz](https://github.com/phorgue/porousMultiphaseFoam/files/3615181/dam_example7.tar.gz)

**Comment by phorgue** [comment]
This issue does not concern the porousMultiphaseFoam toolbox (porousInterFoam is not a solver from the toolbox). Moreover, equations from both solvers are totally different so convergence issues, results and solutions are also totally different.

I close the issue and suggest to create a topic on CFD-online.

Pierre

**Comment by fengzekang** [comment]
Dear @phorgue and @FoamScience 
My meaning is not that ask you help me solve the problem with other application. And I just want to have a talk about the issues with CFDer. 
As for what I mentioned, did you use the tetrahedral grids to do simulation? and can we use the porousMultiphaseFoam to simulate the dam-seepage. if it is, I think I will use this application and make some more developement based on this.
Sorry for my misleading. And I do not have any other thinking but just want to have a discussion with you. Best regards. Thanks.~~
