### ISSUE TITLE
Error when running ./Allwmake to install porousMultiphaseFoam

### ISSUE THREAD

**Issue by jhougaard20** [phorgue/porousMultiphaseFoam#17]
Hello,

I am trying to install these solvers into my v2006 version of OpenFOAM.  I am running wsl on a windows 10 and using ubuntu.  Every time I try to run the command: ./Allwmake, it goes through the whole process but seems to find errors at every turn.  For example: 

It says this a bunch of times:

`In file included from /home/jhougaard/OpenFOAM/OpenFOAM-v2006/src/finiteVolume/lnInclude/fvCFD.H:29:0,
                 from setFieldsFromMNT.C:44:
/home/jhougaard/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude/argList.H:719:14: note: declared here
         bool optionFound(const word& optName) const
              ^~~~~~~~~~~
setFieldsFromMNT.C:72:26: error: ‘class Foam::argList’ has no member named ‘option’; did you mean ‘options’?
         nameField = args.option("field");
                          ^~~~~~
setFieldsFromMNT.C:81:67: warning: ‘T Foam::argList::optionLookupOrDefault(const Foam::word&, const T&) const [with T = double]’ is deprecated: Since 2018-01; use "getOrDefault() method" [-Wdeprecated-declarations]
     scalar offset = args.optionLookupOrDefault<scalar>("offset",0.);`

A lof of things like this:

`/home/jhougaard/OpenFOAM/OpenFOAM-v2006/src/finiteVolume/lnInclude/fvMatrixSolve.C:325:31: note:   candidate expects 0 arguments, 1 provided
make: *** [/home/jhougaard/OpenFOAM/OpenFOAM-v2006/wmake/rules/General/transform:35: /home/jhougaard/OpenFOAM/OpenFOAM-v2006/build/linux64Gcc63DPInt32Opt/pura/porousMultiphaseFoam/solvers/groundwaterTransportFoam/groundwaterTransportFoam.o] Error 1
+ wmake solvers/stationaryGroundwater2DFoam
wmake solvers/stationaryGroundwater2DFoam
g++ -std=c++11 -m64 -pthread -DOPENFOAM=2006 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -Wno-attributes -Wno-unknown-pragmas  -O3  -DNoRepository -ftemplate-depth-100 -DFULLDEBUG -g -O0 -I/home/jhougaard/OpenFOAM/OpenFOAM-v2006/src/finiteVolume/lnInclude -I/home/jhougaard/OpenFOAM/OpenFOAM-v2006/src/meshTools/lnInclude -I../../libraries/porousModels/lnInclude -I../../libraries/toolsGIS/lnInclude -iquote. -IlnInclude -I/home/jhougaard/OpenFOAM/OpenFOAM-v2006/src/OpenFOAM/lnInclude -I/home/jhougaard/OpenFOAM/OpenFOAM-v2006/src/OSspecific/POSIX/lnInclude   -fPIC -c stationaryGroundwater2DFoam.C -o /home/jhougaard/OpenFOAM/OpenFOAM-v2006/build/linux64Gcc63DPInt32Opt/pura/porousMultiphaseFoam/solvers/stationaryGroundwater2DFoam/stationaryGroundwater2DFoam.o
In file included from stationaryGroundwater2DFoam.C:50:0:`

Or: 
`In file included from groundwaterTransportFoam.C:77:0:
setDeltaT.H:160:17: error: ‘class Foam::Time’ has no member named ‘setDeltaTNoAdjust’; did you mean ‘setDeltaT’?
         runTime.setDeltaTNoAdjust(timeToNextEvent/nStepsToNextEvent);
                 ^~~~~~~~~~~~~~~~~
setDeltaT.H:198:17: error: ‘class Foam::Time’ has no member named ‘setDeltaTNoAdjust’; did you mean ‘setDeltaT’?
         runTime.setDeltaTNoAdjust(min(runTime.deltaTValue(),timeToCloseEvent));
                 ^~~~~~~~~~~~~~~~~
In file included from groundwaterTransportFoam.C:106:0:
setDeltaT.H:160:17: error: ‘class Foam::Time’ has no member named ‘setDeltaTNoAdjust’; did you mean ‘setDeltaT’?
         runTime.setDeltaTNoAdjust(timeToNextEvent/nStepsToNextEvent);
                 ^~~~~~~~~~~~~~~~~
setDeltaT.H:198:17: error: ‘class Foam::Time’ has no member named ‘setDeltaTNoAdjust’; did you mean ‘setDeltaT’?
         runTime.setDeltaTNoAdjust(min(runTime.deltaTValue(),timeToCloseEvent));`

Any idea what I could be doing wrong or why it's producing so many errors when I try to run ./Allwmake? 

Thanks,
Jake

**Comment by schrummy14** [comment]
It looks like you are not using a supported version of OpenFOAM.
The code should be valid for up to OpenFOAM-v1906 or OpenFOAM-v7.

**Comment by jhougaard20** [comment]
I am running OpenFOAM-v2006, which is the latest version that came out in June of this year... Is it possible that this latest version is not supported yet?

**Comment by schrummy14** [comment]
Correct, looking at the README file, it says
- The current branches (last version of the toolbox)
  - branch "openfoam-v1906" > PMFv1912
  - branch "openfoam-v7"    > PMFv1912

Unfortunately, I probably will not work on a fix as I use OpenFOAM v5 for my own research and currently have no need for the later versions of OpenFOAM...

**Comment by jhougaard20** [comment]
I see.  No worries, I may just have to download an older version of OpenFOAM so I can use these solvers.  

Is there anywhere I can find documentation on the solvers and what they are specifically used for? Some of them are self explanatory but others are not.  I am trying to model the capillary action in a porous wick along with evaporation of the fluid off the top of the wick and was hoping to use one of these solvers for it.

**Comment by jhougaard20** [comment]
So I downloaded v-1906 and I'm trying to install porousMultiphaseFoam and i'm getting the exact same errors that I was when I tried to install it on v2006.  I'm not sure what else I could try?

**Comment by phorgue** [comment]
You are on the default branch of the repository (openfoam-v7) which is not compatible with your version. You should change to the compatible  branch with :
    git checkout openfoam-v1906
et then
    ./Allwclean
   ./Allwmake
