### ISSUE TITLE
Error on compilation

### ISSUE THREAD

**Issue by alek-** [phorgue/porousMultiphaseFoam#2]
When compiling with OpenFOAM-5.0, the following error occurs:

`phaseModels/incompressiblePhase/incompressiblePhase.C:54:19: error: ‘class Foam::IOobject’ has no member named ‘headerOk’`

**Comment by phorgue** [comment]
Bug fixed by commit 4ef5ffb065f721c6b003a73b5e9affa4ecf4bb78
