### ISSUE TITLE
incompatibility with OpenFOAM 3.0.1 for impesFoam

### ISSUE THREAD

**Issue by Pfiffikus** [phorgue/porousMultiphaseFoam#3]
If we compile  `porousMultiphaseFoam/solvers/impesFoam/SEqn.H` with aforementioned version, at least the newly introduced 'boundaryFieldRef' makes trouble:
`SEqn.H:9:18: Fehler: »Foam::surfaceScalarField {aka class Foam::GeometricField<double, Foam::fvsPatchField, Foam::surfaceMesh>}« has no member named »boundaryFieldRef«
             phia.boundaryFieldRef()[patchi] = Ua.boundaryField()[patchi] & mesh.Sf().boundaryField()[patchi];`

How to solve this issue without switching to `porousMultiphaseFoam/commits/foam-extend/solvers/impesFoam/SEqn.H`?

**Comment by phorgue** [comment]
1st option : switch to of300 branch but you loose all recent developments (and bug corrections).

2nd option : replace boundaryFieldRef() by boundaryField() and ref() by internalField() (this was modified for OpenFOAM 4.0 compatibility)
