### ISSUE TITLE
support dynamicMesh

### ISSUE THREAD

**Issue by shiyezia** [phorgue/porousMultiphaseFoam#30]
Does this supports OpenFOAM dynamicMesh? Thanks

**Comment by phorgue** [comment]
Currently, not. 

However, even if it could be relatively easy to add **fvDynamicMesh** support to the solvers (simply adding **createDynamicFvMesh.H** + **mesh.update()** operation), it is complicated to know if the solver will be able to correctly solve the specific flow equations in porous media. It would require a dedicated study and validation cases. 

Regards,
