### ISSUE TITLE
Build failure with OpenFOAM 9

### ISSUE THREAD

**Issue by robbenmigacz** [phorgue/porousMultiphaseFoam#37]
Hello,

I am attempting to build porousMultiphaseFoam with OpenFOAM 9. I am receiving a number of errors about the type of the argument to `readInt()` when called from `XYfile::readMapping()`:

```
XYfile/XYfile.C: In member function ‘bool Foam::XYfile::readMapping(Foam::IFstream&)’:
XYfile/XYfile.C:229:30: error: invalid initialization of reference of type ‘Foam::Istream&’ from expression of type ‘Foam::string’
         if ((readInt(split[0]) != mesh_.C().size()) || (readInt(split[1]) != npoints_))
                              ^
In file included from <OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/label.H:3,
                 from <OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/HashTable.H:47,
                 from <OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/objectRegistry.H:38,
                 from <OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/polyMesh.H:44,
                 from <OpenFOAM 9 installation path>/src/finiteVolume/lnInclude/fvMesh.H:50,
                 from XYfile/XYfile.H:49,
                 from XYfile/XYfile.C:30:
<OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/int.H:70:5: note: in passing argument 1 of ‘int Foam::readInt(Foam::Istream&)’
 int readInt(Istream&);
     ^~~~~~~

XYfile/XYfile.C:229:73: error: invalid initialization of reference of type ‘Foam::Istream&’ from expression of type ‘Foam::string’
         if ((readInt(split[0]) != mesh_.C().size()) || (readInt(split[1]) != npoints_))
                                                                         ^
In file included from <OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/label.H:3,
                 from <OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/HashTable.H:47,
                 from <OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/objectRegistry.H:38,
                 from <OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/polyMesh.H:44,
                 from <OpenFOAM 9 installation path>/src/finiteVolume/lnInclude/fvMesh.H:50,
                 from XYfile/XYfile.H:49,
                 from XYfile/XYfile.C:30:
<OpenFOAM 9 installation path>/src/OpenFOAM/lnInclude/int.H:70:5: note: in passing argument 1 of ‘int Foam::readInt(Foam::Istream&)’
 int readInt(Istream&);
     ^~~~~~~

…
```

It looks like `readInt()` has an argument of type `Istream&` (https://github.com/OpenFOAM/OpenFOAM-9/blob/master/src/OpenFOAM/primitives/ints/int/int.H#L70), but `split` is initialized as `DynamicList<string> split` (https://github.com/phorgue/porousMultiphaseFoam/blob/openfoam-v9/libraries/toolsGIS/XYfile/XYfile.C#L228). If I'm reading this error correctly, it looks like there's an incompatibility between types.

To build this, I am running

```
# Not shown: Setting up OpenFOAM environment
# Not shown: Cloning porousMultiphaseFoam from GitHub
git switch openfoam-v9  # per Installation/Compatibility section of documentation
./Allwmake
```

on Rocky Linux 8 with OpenFOAM 9 installed via Spack (https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/openfoam-org/package.py). My OpenFOAM installation is working and I have been able to install other open-source solvers with the same build process. Can you please help me identify the cause of this build failure? Thank you!

**Comment by phorgue** [comment]
Hi, 

There were multiple errors due to the history manipulation in the repository and none of the openfoam.org (v8,9,10...) were working. 

I fixed the issue and you can normally compile PMFv2310 using branch openfoam-v9 or openfoam-v10.

However, keep in mind that there are not the "standard" version for PMF developments. If you want the last release (PMFv2406), you should use openfoam.com version (v2106 2206 2306 2406).

**Comment by robbenmigacz** [comment]
Thank you for the quick response. The build is working now.
