### ISSUE TITLE
porousBoundaryConditions library compiling error

### ISSUE THREAD

**Issue by Thomaszsz** [phorgue/porousMultiphaseFoam#6]
Hi,

When compiling porousMultiphaseFoam master branch (I have OpenFoam6 v1806) using the steps provided on 
[https://openfoamwiki.net/index.php/Contrib/porousMultiphaseFoam](https://openfoamwiki.net/index.php/Contrib/porousMultiphaseFoam) 
I encountered an error in the compiler log file.

> /usr/bin/ld: cannot find -lporousBoundaryConditions
> collect2: error: ld returned 1 exit status

This error is very similar to the one posted a few years back on the CFD-online forums.
[https://www.cfd-online.com/Forums/openfoam-community-contributions/159443-difficulties-trying-install-porousmultiphasefoam-openfoam-windows-15-06-a.html](https://www.cfd-online.com/Forums/openfoam-community-contributions/159443-difficulties-trying-install-porousmultiphasefoam-openfoam-windows-15-06-a.html)
The compiler finishes, however the impesFoam solver is not compiled properly and so OpenFoam does not recognize the solver. 

I was wondering if I am doing something wrong, and if there is a fix for this issue. 

Thanks in advance,

**Comment by phorgue** [comment]
Hi, 

the "master" branch is compatible with the OpenFOAM foundation version (openfoam.org)
the esi-version branch is compatible with the OpenFOAM ESI version (openfoam.com)
the foam-extend branch is compatible with the foam-extend version.

Sincerely,

Pierre
