### ISSUE TITLE
Développements

### ISSUE THREAD

**Issue by renardf** [phorgue/porousMultiphaseFoam#8]
- [ ] Groundwater2DFoam : ajouter la gestion de l'épaisseur mouillée minimale, pour éviter l'assèchement des cellules en transitoire d'écoulement
- [ ] GroundwaterFoam : ajout de la condition d'infiltration transitoire homogène et sortie WaterBalance.csv
- [ ] GroundwaterTransportFoam : à mettre à jour avec les nouvelles CL
- [ ] GroundwaterTransport2DFoam : à développer
- [ ] condition d'infiltration transitoire hétérogène
- [ ] améliorer la gestion du pas de temps pour diminuer les temps de calcul
- [ ] publication

**Comment by phorgue** [comment]
splitted in multiple enhancements (#9 #10....)
